echo "- Adding Now Brief Support.."
ADD_TO_WORK_DIR "pa3qxxx" "system" "system/priv-app/SamsungSmartSuggestions/SamsungSmartSuggestions.apk" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "pa3qxxx" "system" "system/etc/default-permissions/default-permissions-com.samsung.android.app.moments.xml" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "pa3qxxx" "system" "system/priv-app/Moments/Moments.apk" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "pa3qxxx" "system" "system/etc/sysconfig/moments.xml" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "pa3qxxx" "system" "system/priv-app/SamsungSmartSuggestions/oat" 0 0 755 "u:object_r:system_data_file:s0"
ADD_TO_WORK_DIR "pa3qxxx" "system" "system/lib64/aidl_comm_iccc_client.so" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "pa3qxxx" "system" "system/lib64/libsmpsft.smps.samsung.so" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "pa3qxxx" "system" "system/lib64/vendor.samsung.hardware.tlc.iccc-V3-ndk.so" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "pa3qxxx" "system" "system/etc/permissions/privapp-permissions-com.samsung.android.app.moments.xml" 0 0 644 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "pa3qxxx" "system" "system/etc/init/init.secpass.rc" 0 0 755 "u:object_r:system_file:s0"
SET_FLOATING_FEATURE_CONFIG "SEC_FLOATING_FEATURE_COMMON_CONFIG_AI_VERSION" "20251"
SET_FLOATING_FEATURE_CONFIG "SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_PERSONALIZED_DATA_CORE" "TRUE"
echo "- Added Now Brief Support!"
