FTP=(
"$APKTOOL_DIR/system/priv-app/SecSettings/SecSettings.apk/smali_classes4/com/samsung/android/settings/deviceinfo/batteryinfo/BatteryRegulatoryPreferenceController.smali"
"$APKTOOL_DIR/system/priv-app/SecSettings/SecSettings.apk/smali_classes4/com/samsung/android/settings/deviceinfo/batteryinfo/SecBatteryFirstUseDatePreferenceController.smali"
"$APKTOOL_DIR/system/priv-app/SecSettings/SecSettings.apk/smali_classes4/com/samsung/android/settings/deviceinfo/batteryinfo/SecBatteryInfoFragment.smali"
)

for f in "${FTP[@]}"; do
    sed -i "s/SM-A236B/SM-A736B/g" "$f"
done

SMALI_FILE="$APKTOOL_DIR/system/framework/services/smali/com/android/server/asks/ASKSManagerService.smali"
if [ -f "$SMALI_FILE" ]; then
    sed -i "s/ro.build.official.release/ro.build.2ndbrand/g" "$SMALI_FILE"
fi

SET_PROP "system" "fw.max_users" "8"
SET_PROP "system" "fw.show_multiuserui" "1"
SET_PROP "system" "persist.device_config.activity_manager_native_boot.use_freezer" "true"

SET_PROP "system" "ro.build.display.id" "KshROM Beta v1.4.0-0972d6ef-a70q+ (AP3A.240905.015.A2.A736BXXUAFYE6)"
SET_PROP "system" "wlan.wfd.hdcp" "disable"

# try to fix black cube
SET_PROP "system" "ro.sf.lcd_density" "420"
SET_PROP "system" "ro.config.main_camera_inset" "0"
SET_PROP "system" "ro.config.front_camera_inset" "0"
SET_PROP "system" "ro.config.no_display_cutout" "true"
SET_PROP "system" "ro.sf.display_cutout" "false"

SET_PROP "system" "dalvik.vm.execution-mode" "int:jit"
SET_PROP "system" "dalvik.vm.heapsize" "512m"
SET_PROP "system" "dalvik.vm.heapstartsize" "16m"
SET_PROP "system" "dalvik.vm.heapgrowthlimit" "192m"
SET_PROP "system" "dalvik.vm.heapminfree" "2m"
SET_PROP "system" "dalvik.vm.heapmaxfree" "8m"
SET_PROP "system" "dalvik.vm.dex2oat-filter" "speed-profile"
SET_PROP "system" "dalvik.vm.verify-bytecode" "false"
SET_PROP "system" "dalvik.vm.stack-trace-file" "/dev/null"
SET_PROP "system" "dalvik.vm.checkjni" "false"
SET_PROP "system" "dalvik.vm.dexopt-data-only" "false"

SET_PROP "system" "persist.sys.background_apps_limit" "25"
SET_PROP "system" "persist.sys.zram.enabled" "true"
SET_PROP "system" "persist.sys.zram.size" "1024M"
SET_PROP "system" "persist.sys.fstrim.enable" "true"
SET_PROP "system" "persist.sys.fstrim_interval" "43200"
SET_PROP "system" "persist.sys.low_ram" "false"
SET_PROP "system" "persist.sys.app_oom_adj" "0"

SET_PROP "system" "persist.sys.cpufreq.governor" "schedutil"
SET_PROP "system" "persist.sys.cpufreq.min_freq" "600000"
SET_PROP "system" "persist.sys.cpufreq.max_freq" "2200000"
SET_PROP "system" "persist.sys.cpufreq.boost" "true"
SET_PROP "system" "persist.sys.cpufreq.up_threshold" "55"
SET_PROP "system" "persist.sys.cpufreq.down_threshold" "25"
SET_PROP "system" "persist.sys.cpufreq.io_is_busy" "true"
SET_PROP "system" "persist.sys.cpufreq.sched_boost" "1"
SET_PROP "system" "persist.sys.cpufreq.sched_migration_fixup" "1"
SET_PROP "system" "persist.sys.cpufreq.sched_upmigrate" "85"
SET_PROP "system" "persist.sys.cpufreq.sched_downmigrate" "75"

SET_PROP "system" "persist.sys.gpu.governor" "simple_ondemand"
SET_PROP "system" "persist.sys.gpu.min_freq" "300000000"
SET_PROP "system" "persist.sys.gpu.max_freq" "750000000"
SET_PROP "system" "persist.sys.gpu.scaling_boost" "1"

SET_PROP "system" "net.tcp.buffersize.default" "4096,87380,8388608,4096,16384,8388608"
SET_PROP "system" "net.tcp.buffersize.wmem_default" "4096"
SET_PROP "system" "net.tcp.buffersize.rmem_default" "4096"
SET_PROP "system" "net.tcp.buffersize.wmem_max" "8388608"
SET_PROP "system" "net.tcp.buffersize.rmem_max" "8388608"
SET_PROP "system" "net.ipv4.tcp_window_scaling" "1"
SET_PROP "system" "net.ipv4.tcp_congestion_control" "hybla"
SET_PROP "system" "net.ipv4.tcp_slow_start_after_idle" "0"
SET_PROP "system" "net.ipv4.tcp_low_latency" "1"
SET_PROP "system" "net.ipv4.tcp_adv_win_scale" "1"

SET_PROP "system" "persist.sys.use_power_saving" "false"
SET_PROP "system" "persist.sys.battery_saver" "false"
SET_PROP "system" "ro.config.hw_power_saving" "false"
SET_PROP "system" "ro.config.low_power" "false"
SET_PROP "system" "persist.sys.strictmode.disable" "true"

SET_PROP "system" "log.tag.SF" "false"
SET_PROP "system" "log.tag.ActivityManager" "false"
SET_PROP "system" "log.tag.PackageManager" "false"
SET_PROP "system" "log.tag.AudioFlinger" "false"
SET_PROP "system" "log.tag.InputMethodManager" "false"

SET_PROP "system" "persist.sys.io.scheduler" "deadline"
SET_PROP "system" "persist.sys.fstrim.interval" "604800"

SET_PROP "system" "ro.adb.secure" "0"
SET_PROP "system" "ro.secure" "1"
SET_PROP "system" "ro.debuggable" "0"
SET_PROP "system" "persist.sys.check_apps_install" "1"
SET_PROP "system" "persist.sys.max_fling_velocity" "8000"
SET_PROP "system" "persist.sys.min_fling_velocity" "400"

SET_PROP "system" "persist.sys.window_animation_scale" "0.5"
SET_PROP "system" "persist.sys.transition_animation_scale" "0.5"
SET_PROP "system" "persist.sys.animator_duration_scale" "0.5"
SET_PROP "system" "persist.sys.hwui.renderer" "skiagl"
SET_PROP "system" "persist.sys.hwui.render_dirty_regions" "false"
SET_PROP "system" "persist.sys.hwui.texture_cache_size" "72"
SET_PROP "system" "persist.sys.hwui.layer_cache_size" "36"
SET_PROP "system" "persist.sys.hwui.r_buffer_cache_size" "16"
SET_PROP "system" "persist.sys.hwui.drop_shadow_cache_size" "4"
SET_PROP "system" "persist.sys.hwui.gradient_cache_size" "8"
SET_PROP "system" "persist.sys.preload_apps" "1"
SET_PROP "system" "persist.sys.preload_app_limit" "6"
SET_PROP "system" "persist.sys.home_drawer_cache_size" "32"
SET_PROP "system" "persist.sys.home_grid_refresh_rate" "60"
SET_PROP "system" "persist.sys.home_animation_boost" "1"
SET_PROP "system" "persist.sys.home_fling_smooth" "1"
