ADD_TO_WORK_DIR "a70q" "system" "system/app/NfcNci/NfcNci.apk"
ADD_TO_WORK_DIR "a70q" "system" "system/app/NfcNci/lib/arm64/libnfc_nci_jni.so"
ADD_TO_WORK_DIR "a70q" "system" "system/etc/permissions/com.android.nfc_extras.xml"
ADD_TO_WORK_DIR "a70q" "system" "system/etc/permissions/com.publicnfc.xml"
ADD_TO_WORK_DIR "a70q" "system" "system/etc/permissions/com.samsung.android.nfc.rfcontrol.xml"
ADD_TO_WORK_DIR "a70q" "system" "system/etc/permissions/com.samsung.android.nfc.t4t.xml"
ADD_TO_WORK_DIR "a70q" "system" "system/etc/permissions/com.sec.feature.nfc_authentication.xml"
ADD_TO_WORK_DIR "a70q" "system" "system/etc/nfcee_access.xml"
ADD_TO_WORK_DIR "a70q" "system" "system/framework/com.android.nfc_extras.jar"
ADD_TO_WORK_DIR "a70q" "system" "system/framework/com.publicnfc.jar"
ADD_TO_WORK_DIR "a70q" "system" "system/framework/com.samsung.android.nfc.rfcontrol.jar"
ADD_TO_WORK_DIR "a70q" "system" "system/framework/com.samsung.android.nfc.t4t.jar"
ADD_TO_WORK_DIR "a70q" "system" "system/lib/android.hardware.bluetooth@1.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib/android.hardware.bluetooth@1.1.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib/android.hardware.bluetooth.a2dp@1.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib/android.hardware.bluetooth.audio@2.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib/android.hardware.nfc@1.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib/android.hardware.nfc@1.1.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib/android.hardware.nfc@1.2.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib/hw/audio.a2dp.default.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/android.hardware.bluetooth@1.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/android.hardware.bluetooth@1.1.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/android.hardware.bluetooth.a2dp@1.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/android.hardware.bluetooth.audio@2.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/android.hardware.nfc@1.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/android.hardware.nfc@1.1.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/android.hardware.nfc@1.2.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/libbluetooth_jni.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/libbluetooth.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/libnfc_nci_jni.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/libnfc-nci.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/libNfcProperties.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/vendor.nxp.nxpnfc@1.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/vendor.nxp.nxpnfc@1.1.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/vendor.samsung.hardware.bluetooth.a2dp@1.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/vendor.samsung.hardware.bluetooth.a2dpsink@1.0.so"
ADD_TO_WORK_DIR "a70q" "system" "system/lib64/hw/audio.a2dp.default.so"
echo "added a70q hals"






